swagger: '2.0'
info:
  version: '1.0.0'
  title: User Management API
  description: API to manage users
  termsOfService: none
  contact:
    name: Nikolaos Garanis, Samuel Mettler
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
basePath: /api
schemes:
  - http
paths:
  /public/authenticate:
    post:
      tags:
        - public
      summary: Authenticate user.
      description: Allows a user to authentication itself.
      consumes:
        - application/json
      parameters:
        - name: identifiers
          in: body
          required: true
          schema:
            $ref: '#/definitions/identifiers'
      responses:
        200:
          description: User is authenticated.
          schema:
            $ref: '#/definitions/token'
        401:
          description: Wrong authentication values.
  /private/password:
    put:
      tags:
        - private
      summary: Update a user password.
      description: Allows a user to modify his own password.
      consumes:
        - application/json
      parameters:
        - name: password
          in: body
          required: true
          schema:
            $ref: '#/definitions/password'
      responses:
        200:
          description: Password updated.
  /admin/users:
    post:
      tags:
        - admin
      summary: Create a user account.
      description: Allows an admin to create a new user account.
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        201:
          description: User created.
        401:
          description: Admin not authentified.
        409:
          description: User already exists.
definitions:
  identifiers:
    type: object
    required:
      - email
      - password
    properties:
      email:
        $ref: '#/definitions/email'
      password:
        $ref: '#/definitions/password'
  user:
    allOf:
      - $ref: '#/definitions/identifiers'
      - type: object
        required:
          - firstName
          - lastName
          - blocked
          - role
    properties:
      email:
        $ref: '#/definitions/email'
      firstName:
        type: string
      lastName:
        type: string
      password:
        $ref: '#/definitions/password'
      blocked:
        type: boolean
      role:
        type: string
  password:
    type: string
  email:
    type: string
  token:
    type: object
    required:
      - token
    properties:
      token:
        type: string
